DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
INITIALDIR=$PWD
export ANCHOR_PATH=$DIR/ANCHOR
export IUPred_PATH=$DIR/iupred
export PASTA_PATH=$DIR/PASTA/pasta_exe
cd $DIR/ANCHOR
make clean
make
cd $DIR/iupred
gcc iupred.c -o iupredExe
export PROSITE=$DIR/ps_scan
cd $INITIALDIR
export HEMO="MVLSPADKTNVKAAWGKVGAHAGEYGAEALERMFLSFPTTKTYFPHFDLSHGSAQVKGHGKKVADALTNAVAHVDDMPNALSALSDLHAHKLRVDPVNFKLLSHCLLVTLAAHLPAEFTPAVHASLDKFLASVSTVLTSKYR"
